export const PIXEL_BANNER_PLUS = {
    API_URL: 'https://pixel-banner.online/',
    // API_URL: 'http://localhost:3000/',
    ENDPOINTS: {
        PING: 'ping',
        VERIFY: 'verify',
        TEXT_TO_IMAGE_MODELS: 'text-to-image-models',
        UPLOAD_TEMP_IMAGE: '/upload-temp-image',
        GENERATE: 'generatev2',
        GENERATE_BANNER_IDEA: 'generate-banner-idea',
        GENERATE_BANNER_IDEA_FROM_SEED: 'generate-banner-idea-from-seed',
        REWRITE_BANNER_IDEA: 'rewrite-banner-idea',
        HISTORY: 'history',
        HISTORY_COUNT: 'history/count',
        HISTORY_PAGE: 'history/page',
        HISTORY_DELETE: 'history/image',
        STORE_CATEGORIES: 'store-categories',
        STORE_CATEGORY_IMAGES: 'store-category-images',
        STORE_IMAGE_BY_ID: 'store-image-by-id',
        STORE_IMAGE_SEARCH: 'store-search',
        SIGNUP: 'signup',
        BANNER_VOTES_STATS: 'api/banner-votes/:id/stats',
        BANNER_VOTES_USER_VOTE: 'api/banner-votes/:id/user-vote',
        BANNER_VOTES_UPVOTE: 'api/banner-votes/:id/upvote',
        BANNER_VOTES_DOWNVOTE: 'api/banner-votes/:id/downvote',
        INFO: 'api/pixel-banner-info',
        DAILY_GAME: 'games/daily-embed',
        BANNER_ICON_CATEGORIES: 'api/icon-categories',
        BANNER_ICONS: 'api/banner-icons',
        BANNER_ICONS_SEARCH: 'api/banner-icons/search',
        BANNER_ICONS_ID: 'api/banner-icons/:id',
    },
    SHOP_URL: 'https://ko-fi.com/s/7ce609ff2c',
    DONATE_URL: 'https://ko-fi.com/jparkerweb',
    BANNER_ICON_KEY: 'pixel-banner-icons'
};
